services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules # Prevents host node_modules overwriting container's
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents host node_modules overwriting container's
    command: npm run dev -- --host